#pragma once

#include "vehExtParams.h"

#include <map>

extern void(__cdecl* g_pfnVehProcessControlAddon[0x10])(CVehicle*, CVehExtParams::Params*);
extern uint8_t g_numVehProcessControlAddon;

extern void(__cdecl* g_pfnVehPrerenderAddon[0x10])(CVehicle*, CVehExtParams::Params*);
extern uint8_t g_numVehPrerenderAddon;


enum eNewComponents : char {
	COMPONENT_STEER_FIRST,
	COMPONENT_STEER_1 = COMPONENT_STEER_FIRST,
	COMPONENT_STEER_2,
	COMPONENT_STEER_LAST = COMPONENT_STEER_2,
	COMPONENT_SPEED_FIRST,
	COMPONENT_SPEED_1 = COMPONENT_SPEED_FIRST,
	COMPONENT_SPEED_2,
	COMPONENT_SPEED_LAST = COMPONENT_SPEED_2,
	COMPONENT_TEMP_FIRST,
	COMPONENT_TEMP_1 = COMPONENT_TEMP_FIRST,
	COMPONENT_TEMP_2,
	COMPONENT_TEMP_LAST = COMPONENT_TEMP_2,
	COMPONENT_RPM_FIRST,
	COMPONENT_RPM_1 = COMPONENT_RPM_FIRST,
	COMPONENT_RPM_2,
	COMPONENT_RPM_LAST = COMPONENT_RPM_2,
	COMPONENT_ENGINE_FIRST,
	COMPONENT_ENGINE_1 = COMPONENT_ENGINE_FIRST,
	COMPONENT_ENGINE_2,
	COMPONENT_ENGINE_LAST = COMPONENT_ENGINE_2,
	COMPONENT_SUPERCHARGER_THROTTLE_FIRST,
	COMPONENT_SUPERCHARGER_THROTTLE_0 = COMPONENT_SUPERCHARGER_THROTTLE_FIRST,
	COMPONENT_SUPERCHARGER_THROTTLE_1,
	COMPONENT_SUPERCHARGER_THROTTLE_2,
	COMPONENT_SUPERCHARGER_THROTTLE_3,
	COMPONENT_SUPERCHARGER_THROTTLE_LAST = COMPONENT_SUPERCHARGER_THROTTLE_3,
	COMPONENT_POPUP_HEADLIGHTS,
	COMPONENT_PLATELIGHT_FIRST,
	COMPONENT_PLATELIGHT = COMPONENT_PLATELIGHT_FIRST,
	COMPONENT_PLATELIGHT_2,
	COMPONENT_PLATELIGHT_3,
	COMPONENT_PLATELIGHT_4,
	COMPONENT_PLATELIGHT_LAST = COMPONENT_PLATELIGHT_4,

	COMPONENT_EXHAUST_FIRST,
	COMPONENT_EXHAUST = COMPONENT_EXHAUST_FIRST,
	COMPONENT_EXHAUST_2,
	COMPONENT_EXHAUST_3,
	COMPONENT_EXHAUST_4,
	COMPONENT_EXHAUST_5,
	COMPONENT_EXHAUST_6,
	COMPONENT_EXHAUST_7,
	COMPONENT_EXHAUST_8,
	COMPONENT_EXHAUST_9,
	COMPONENT_EXHAUST_10,
	COMPONENT_EXHAUST_11,
	COMPONENT_EXHAUST_12,
	COMPONENT_EXHAUST_13,
	COMPONENT_EXHAUST_14,
	COMPONENT_EXHAUST_15,
	COMPONENT_EXHAUST_16,
	COMPONENT_EXHAUST_LAST = COMPONENT_EXHAUST_16,

	COMPONENT_TANK_ROLL_L_FIRST,
	COMPONENT_TANK_ROLL_1_L = COMPONENT_TANK_ROLL_L_FIRST,
	COMPONENT_TANK_ROLL_2_L,
	COMPONENT_TANK_ROLL_3_L,
	COMPONENT_TANK_ROLL_4_L,
	COMPONENT_TANK_ROLL_5_L,
	COMPONENT_TANK_ROLL_L_LAST = COMPONENT_TANK_ROLL_5_L,

	COMPONENT_TANK_ROLL_R_FIRST,
	COMPONENT_TANK_ROLL_1_R = COMPONENT_TANK_ROLL_R_FIRST,
	COMPONENT_TANK_ROLL_2_R,
	COMPONENT_TANK_ROLL_3_R,
	COMPONENT_TANK_ROLL_4_R,
	COMPONENT_TANK_ROLL_5_R,
	COMPONENT_TANK_ROLL_R_LAST = COMPONENT_TANK_ROLL_5_R,

	COMPONENT_TANK_DRIVE_L_FIRST,
	COMPONENT_TANK_DRIVE_1_L = COMPONENT_TANK_DRIVE_L_FIRST,
	COMPONENT_TANK_DRIVE_2_L,
	COMPONENT_TANK_DRIVE_L_LAST= COMPONENT_TANK_DRIVE_2_L,

	COMPONENT_TANK_DRIVE_R_FIRST,
	COMPONENT_TANK_DRIVE_1_R = COMPONENT_TANK_DRIVE_R_FIRST,
	COMPONENT_TANK_DRIVE_2_R,
	COMPONENT_TANK_DRIVE_R_LAST= COMPONENT_TANK_DRIVE_2_R,

	COMPONENT_WEAPON_FIRST,
	COMPONENT_WEAPON_A = COMPONENT_WEAPON_FIRST,
	COMPONENT_WEAPON_B,
	COMPONENT_WEAPON_C,
	COMPONENT_WEAPON_D,
	COMPONENT_WEAPON_E,
	COMPONENT_WEAPON_F,
	COMPONENT_WEAPON_G,
	COMPONENT_WEAPON_H,
	COMPONENT_WEAPON_I,
	COMPONENT_WEAPON_J,
	COMPONENT_WEAPON_LAST = COMPONENT_WEAPON_J,

	COMPONENT_TURRET_1BASE,
	COMPONENT_TURRET_1BARREL,
	COMPONENT_TURRET_2BASE,
	COMPONENT_TURRET_2BARREL,

	NUM_COMPONENTS,
};

struct alignas(0x10) CVehStruct2 {
	short m_aBones[NUM_COMPONENTS];
	float m_TrackDriveWheelScale[2];
};

extern std::map<uint16_t, CVehStruct2*> g_vehStruct2;

void __cdecl checkVehStruct2(CVehicle* _a, CVehExtParams::Params* pParams);
void __cdecl updateDashboard(CVehicle* _a, CVehExtParams::Params* pParams);
void __cdecl prerenderDashboard(CVehicle* _a, CVehExtParams::Params* pParams);
void __cdecl checkVehStruct2(CVehicle* _a, CVehExtParams::Params* pParams);
void __cdecl checkVehStruct2(CVehicle* _a, CVehExtParams::Params* pParams, uint32_t modelId);

void initNewComponents();
